---

name: Cargo CI

on:
  push:
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make check-ci
      - run: make fmt
      - run: make clippy
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - run: make test-ci
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo install cargo-audit --locked
      - run: make audit
  # deny:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: EmbarkStudios/cargo-deny-action@v2
  #       with:
  #         command: check advisories bans sources
